### ISSUE TITLE
Start_row

### ISSUE THREAD

**Issue by Lynn-Scales** [kneasle/ringing#336]
I'm using V14.5 and I'm struggling with the start_row function.  I'm composing for Surprise Major and I have a line

start_row = "12346578"

in the toml file.  When I run the file Monument tells me that 

Error: Not enough method counts; the composition needs at least 1280 rows but the methods can make at most 0.

If I remove the start_row line it runs fine!

Is this a bug or am I missing some other lines or syntax in my toml file?

Cheers,

Lynn

**Comment by kneasle** [comment]
Huh that's strange.  The error makes me think that Monument is somehow 'proving' that rounds is unreachable, which makes it delete the entirety of its search graph because nothing can reach rounds.  Thus, after that, the max method count is 0 because there's nothing to ring.

Do you have a full file which reproduces this?  Feel free to email it to me directly if you don't want to share what you're working on with the wider internet...

Cheers,

Ben

**Comment by Lynn-Scales** [comment]
So here's a toml file that spits up the error:
=============================
length = 1280

start_row = "12346578"

method = "Yorkshire Surprise Major"

split_tenors = true

base_music = "complib"

base_calls = "none"

[[calls]]
place_notation = "14"
symbol = "-"
weight = -20

[[calls]]
place_notation = "1456"
symbol = "s"
weight = -20
======================================
Rounds is clearly reachable by using, for example, 3B M H W HHsH.

Such fun!

**Comment by kneasle** [comment]
Hi again, I've finally had a chance to look into this properly as I was moving house last week.  This appears to be an oversight on my part when writing the method proving code, where Monument would forget to add method counts if `start_row` and `end_row` aren't identical and there's only one method.  I've fixed it in #337 and I will make a release for v0.15.0 with it, hopefully in the next few days.

Thanks for letting me know about this, and feel free to send me any other possible bugs :)

**Comment by Lynn-Scales** [comment]
Thanks Ben.  Glad to know it wasn't something I wasn't doing and that you could find the bug so quickly.  Looking forward to the next version :-)
